# Generated by Django 5.1.15 on 2026-02-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('color', models.CharField(help_text='Tailwind gradient classes', max_length=100)),
                ('bg_color', models.CharField(blank=True, max_length=100)),
                ('border_color', models.CharField(blank=True, max_length=100)),
                ('text_color', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('guidelines', models.JSONField(default=list, help_text='Dietary guideline strings')),
                ('hero_image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Health Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(help_text='Path relative to frontend public/', max_length=255)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('health_badges', models.JSONField(default=list, help_text='List of badge slugs, e.g. heart-healthy')),
                ('warnings', models.JSONField(default=list, help_text='List of warning strings or objects {type, message}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.healthcategory')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(max_length=50)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('total_fat', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('trans_fat', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('cholesterol', models.PositiveIntegerField(default=0, help_text='mg')),
                ('sodium', models.PositiveIntegerField(default=0, help_text='mg')),
                ('total_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('potassium', models.PositiveIntegerField(default=0, help_text='mg')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.product')),
            ],
            options={
                'verbose_name': 'Nutrition Facts',
                'verbose_name_plural': 'Nutrition Facts',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for allergen/warning')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardiovascular', models.PositiveIntegerField(default=0, help_text='0–100 suitability score')),
                ('diabetes', models.PositiveIntegerField(default=0, help_text='0–100 suitability score')),
                ('hypertension', models.PositiveIntegerField(default=0, help_text='0–100 suitability score')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suitability', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Suitabilities',
            },
        ),
    ]
